# ORACLE
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.31.10.124:1521/orcl
#    username: HdelPG
#    password: vesselInsight

# H2
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

server:
  port: 8080

# MS-SQL
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;databasename=HdelPG
    username: sa
    password: vesselInsight


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

#  jackson:
#    SERIALIZATION:
#      FAIL_ON_EMPTY_BEANS: false
